### ISSUE TITLE
Install fails without psycopg2 (sqlite is available)

### ISSUE THREAD

**Issue by jean** [rolobio/DictORM#40]
It looks like this is due to these lines in `pg.py`:

```python
from psycopg2.extensions import cursor                                                                                                             
mogrify = cursor.mogrify
```

It doesn't look like `mogrify` is used anywhere.

Here's the error:

```shell
$ pip install --user dictorm
Collecting dictorm
  Downloading dictorm-3.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/data/data/com.termux/files/tmp/pip-build-0txo2_cf/dictorm/dictorm/dictorm.py", line 10, in <module>
        from dictorm.pg import Select, Insert, Update, Delete, And
      File "/data/data/com.termux/files/tmp/pip-build-0txo2_cf/dictorm/dictorm/pg.py", line 8, in <module>
        from psycopg2.extensions import cursor
    ModuleNotFoundError: No module named 'psycopg2'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/com.termux/files/tmp/pip-build-0txo2_cf/dictorm/dictorm/__init__.py", line 2, in <module>
        from dictorm.dictorm import * # pragma: no cover
      File "/data/data/com.termux/files/tmp/pip-build-0txo2_cf/dictorm/dictorm/dictorm.py", line 16, in <module>
        from .pg import Select, Insert, Update, Delete, And
      File "/data/data/com.termux/files/tmp/pip-build-0txo2_cf/dictorm/dictorm/pg.py", line 8, in <module>
        from psycopg2.extensions import cursor
    ModuleNotFoundError: No module named 'psycopg2'
```

**Comment by rolobio** [comment]
DictORM requires either psycopg2 or sqlite3 to be installed.  Do you have either installed?  Can you do a `pip freeze` ?

**Comment by jean** [comment]
`sqlite3` is available and that works fine, I just mean that install shouldn't fail because `psycopg2` is not available ---  since we aren't necessarily going to use it (e.g. in my case I'd use `sqlite3`).

**Comment by rolobio** [comment]
I see. It should function with either sqlite3 or psycopg2 installed only.  I'll have to try sqlite3 only tomorrow.  Thanks for the heads up.

**Comment by jean** [comment]
Welcome :-) Thanks for an interesting package. 

Maybe postgres can go into an `extras_require` specification ([ref](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)).

**Comment by rolobio** [comment]
I've made some simple changes in pull request #42 does it work in your environment?

Thanks for the `extras_require` suggestion!
